apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: mubarakbunza/flask-app:latest
        env:
        - name: WELCOME_MSG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: welcome-msg
        ports:
        - containerPort: 5000